[technote]
id = "SQR-089"
series_id = "SQR"
canonical_url = "https://sqr-089.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-089"
github_default_branch = "main"
date_created = 2024-08-06T23:20:24Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
internal_id = "fuchsds"
orcid = "https://orcid.org/0009-0007-2454-1951"
name = {given = "Dan C.", family = "Fuchs"}

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
ror = "https://ror.org/05gzmn429"
[[technote.authors]]
internal_id = "economouf"
orcid = "https://orcid.org/0000-0002-8333-7615"

name = {given = "Frossie", family = "Economou"}
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
ror = "https://ror.org/048g3cy84"

[[technote.status.superseding_urls]]
url = "https://sqr-061.lsst.io/"
